#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorPotentiometer)
#pragma config(Sensor, in3,    ,               sensorPotentiometer)
#pragma config(Sensor, in4,    ,               sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ,               sensorDigitalIn)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Include Replay data reader
#include "ReplayReader.h"

//Replay controller includes
#include "CombinedReplay.h"
//#include "SwivelPidReplay.h"

void doAutonomous(){
	writeDebugStreamLine("(%s,%d): Entering doAutonomous routine",__FILE__,__LINE__);
	startTask(ReplayReader);
	startTask(combinedReplay);
	//startTask(swivelPidReplay);
	writeDebugStreamLine("(%s,%d): Finishing doAutonomous routine, entering infinite sleep",__FILE__,__LINE__);
	while(true){
		sleep(1000);
	}
	writeDebugStreamLine("(%s,%d): Exiting doAutonomous routine",__FILE__,__LINE__);
}
