#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorPotentiometer)
#pragma config(Sensor, in3,    ,               sensorPotentiometer)
#pragma config(Sensor, in4,    ,               sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ,               sensorDigitalIn)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Launch Debugger windows
#pragma DebuggerWindows("vexCompetitionControl")
#pragma DebuggerWindows("debugStream")
#pragma DebuggerWindows("vexLCD")

//Set debug variable - CHANGE BEFORE COMPETITION
//const bool DEBUG = false;
#define DEBUG 0

#if DEBUG
#warn "Don't forget to turn off DEBUG"
#endif

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous a nd usercontrol tasks will not be started.  This      */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	clearDebugStream();
	writeDebugStreamLine("(%s,%d): Battery level at %1.2fV ",__FILE__,__LINE__,nImmediateBatteryLevel/1000.0);
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	bDisplayCompetitionStatusOnLcd = true;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	//DO NOTHING
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

const int mogoPowerUp = -64;
const int mogoPowerDown = 64;

task usercontrol()
{
	writeDebugStreamLine("(%s,%d): Entering usercontrol task ",__FILE__,__LINE__);
	bool slowChain = false;
	while(true){
		float multiplier = vexRT[Btn5U] ? 1: 0.6;
		float chainModifier = slowChain ? 0.5 : 1.0;
		motor[port3] = (vexRT[Ch3] + vexRT[Ch4]) * multiplier;
		motor[port4] = ((vexRT[Ch3] + vexRT[Ch4]) * multiplier) * chainModifier;
		motor[port7] = -1*(((vexRT[Ch3] - vexRT[Ch4]) * multiplier) * chainModifier);
		motor[port8] = -1*((vexRT[Ch3] - vexRT[Ch4]) * multiplier);
		if(vexRT[Btn6U]){
			motor[port2] = -1 * mogoPowerUp;
			motor[port9] = mogoPowerUp;
		}else if(vexRT[Btn6D]){
			motor[port2] = -1 * mogoPowerDown;
			motor[port9] = mogoPowerDown;
		}else{
			motor[port2] = 0;
			motor[port9] = 0;
		}
		if(vexRT[Btn8R]){
			 	slowChain = true;
		}
	}
}
