#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorPotentiometer)
#pragma config(Sensor, in3,    ,               sensorPotentiometer)
#pragma config(Sensor, in4,    ,               sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ,               sensorDigitalIn)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Launch Debugger windows
#pragma DebuggerWindows("vexCompetitionControl")
#pragma DebuggerWindows("debugStream")
//#pragma DebuggerWindows("vexLCD")

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

//Driver control include
#include "DriverControl.h"

//Autonomous include
#include "Autonomous.h"

//Programmer Skills include
#include "ProgrammerSkills.h"

//Debug include
#include "Debug.h"

//Util include
#include "Util.h"

//Set debug variable - CHANGE BEFORE COMPETITION
#define AT_COMPETITION false
const bool DEBUG = false;


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous a nd usercontrol tasks will not be started.  This      */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	clearDebugStream();
	writeDebugStreamLine("(%s): Entering pre_auton task ",__FILE__);
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	bDisplayCompetitionStatusOnLcd = true;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
	writeDebugStreamLine("(%s): Exiting pre_auton task ",__FILE__);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	writeDebugStreamLine("(%s): Entering autonomous task ",__FILE__);
	writeDebugStreamLine("(%s): Running stopAllUserCreatedTasks routine ",__FILE__);
	stopAllUserCreatedTasks();
	writeDebugStreamLine("(%s): Done running stopAllUserCreatedTasks routine ",__FILE__);
	if(SensorValue[dgtl1]){
		writeDebugStreamLine("(%s): Running doProgrammerSkills routine",__FILE__);
		doProgrammerSkills();
		writeDebugStreamLine("(%s): Done running doProgrammerSkills routine",__FILE__);
	}else{
		writeDebugStreamLine("(%s): Running doAutonomous routine",__FILE__);
		doAutonomous();
		writeDebugStreamLine("(%s): Done running doAutonomous routine",__FILE__);
	}
	writeDebugStreamLine("(%s): Exiting autonomous task ",__FILE__);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	writeDebugStreamLine("(%s): Entering usercontrol task ",__FILE__);
	writeDebugStreamLine("(%s): Running stopAllUserCreatedTasks routine ",__FILE__);
	stopAllUserCreatedTasks();
	writeDebugStreamLine("(%s): Done running stopAllUserCreatedTasks routine ",__FILE__);
	if(DEBUG&&!AT_COMPETITION){
		writeDebugStreamLine("(%s): Running doDebug routine ",__FILE__);
		doDebug();
		writeDebugStreamLine("(%s): Done running doDebug routine ",__FILE__);
	}else{
		writeDebugStreamLine("(%s): Running doDriverControl routine ",__FILE__);
		doDriverControl();
		writeDebugStreamLine("(%s): Done running doDriverControl routine ",__FILE__);
	}
	writeDebugStreamLine("(%s): Exiting usercontrol task ",__FILE__);
}
