#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorPotentiometer)
#pragma config(Sensor, in3,    ,               sensorPotentiometer)
#pragma config(Sensor, in4,    ,               sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ,               sensorDigitalIn)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define _getCurrentSwivelValue() (4095 - (SensorValue[in1]) + (SensorValue[in2]) )/2

void doDebug(){
	writeDebugStreamLine("(%s,%d): Entering doDebug routine",__FILE__,__LINE__);
	startTask(swivelPidController);
	startTask(driveTrainController);
	clearLCDLine(0);
	clearLCDLine(1);
	while(true){
		writeDebugStreamLine("(%s,%d): %d, %d",__FILE__,__LINE__,SensorValue[in1],SensorValue[in2]);
		displayLCDNumber(1,1,10000+_getCurrentSwivelValue());
		sleep(100);

	}
}
